### ISSUE TITLE
Implement hex grid function

### ISSUE THREAD

**Issue by Robinlovelace** [isonoi/isonoi#1]
First port of call: h3o

Heads-up @JosiahParry here's a use case for you, and maybe a motivator for getting this published on CRAN which I'm happy to help with.

Need to check it actually works for our use case first, hope so!

**Comment by JosiahParry** [comment]
Thank you! I'm working through the last kinks of rsgeo on CRAN. Once I get that sorted out h3o will be heading over!

**Comment by Robinlovelace** [comment]
Great stuff, thanks! Quick question: how do we create h3 cells covering a given case study region?

**Comment by Robinlovelace** [comment]
We have an `sf` object called `poly` and want a load of h3 cells. See here for some pictures, reprex incoming...

https://github.com/streetvoronoi/streetvoronoi/#nearest-hex-cells

**Comment by Robinlovelace** [comment]
``` r
# Aim: test the h3o R package

# Starting point: hex grids in sf
remotes::install_github("isonoi/isonoi")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'isonoi' from a github remote, the SHA1 (01c09944) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(isonoi)
library(sf)
#> Linking to GEOS 3.11.1, GDAL 3.6.4, PROJ 9.1.1; sf_use_s2() is TRUE
hex_grid = stplanr::geo_projected(
  net_oldenburg_raw,
  sf::st_make_grid,
  cellsize = 200,
  square = FALSE
)
hex_grid_smaller = hex_grid[net_oldenburg_raw]
plot(hex_grid)
plot(hex_grid_smaller, add = TRUE, col = "red")
plot(net_oldenburg_raw, add = TRUE, col = "blue")
#> Warning in plot.sf(net_oldenburg_raw, add = TRUE, col = "blue"): ignoring all
#> but the first attribute
```

![](https://i.imgur.com/qL1bAlE.png)

<sup>Created on 2023-09-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by JosiahParry** [comment]
`sfc_to_cells()` is the magic one here. However, it wasn't exported. I just pushed it to R-universe so it might take a while to build. You can get it from h3o using `h3o:::sfc_to_cells()` or `getFromNamespace()` (spell check there) for the time being. 

Since its H3 it requires 4326 (or anything using long lat degrees).

I'll polish it up soon!

```r
library(h3o)

polys <- sfdep::guerry$geometry |> 
  sf::st_set_crs(27572) |> 
  sf::st_transform(4326)

poly_cells <- sfc_to_cells(polys, 3)

plot(polys)
plot(flatten_h3(poly_cells), add = TRUE)
```

![](https://i.imgur.com/U5ALzkj.png)

<sup>Created on 2023-09-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Robinlovelace** [comment]
Amazing. Thanks!

**Comment by Robinlovelace** [comment]
Needs exporting : )

**Comment by JosiahParry** [comment]
agreed! 69dd328ce949152545dc70d4171aa53eff0278db

**Comment by JosiahParry** [comment]
agreed! https://github.com/JosiahParry/h3o/commit/69dd328ce949152545dc70d4171aa53eff0278db

**Comment by JosiahParry** [comment]
it should be super quick! @grim7reaper updated the aglorithm to convert geometries to cells and I find it insanely fast. If you find it slow-ish in any regard let me know and I can slap some multi-threading on it.
